name: release-D-kraken

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.KRAKEN_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.KRAKEN_AWS_KEY }}
          aws-region: ${{ secrets.KRAKEN_AWS_REGION }}
      - name: Building the kraken
        run: npm install && npm run build
      - name: releasing D kraken to bucket
        run: aws s3 sync ./dist/ s3://testingkraken --delete
